-- db/changelog/changes/002-create-tables.sql

-- liquibase formatted sql

-- changeset albert:1-create-roles-table
CREATE TABLE IF NOT EXISTS roles(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);
-- rollback DROP TABLE roles;

-- changeset albert:2-create-users-table
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL REFERENCES roles(id)
);
CREATE INDEX idx_users_username ON users(username);
-- rollback DROP TABLE users;

-- changeset albert:3-create-user-details-table
CREATE TABLE IF NOT EXISTS user_details(
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    balance DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(3, 2) CHECK (discount BETWEEN 0 AND 1)
);
-- rollback DROP TABLE user_details;

-- changeset albert:4-create-scopes-table
CREATE TABLE IF NOT EXISTS scopes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
-- rollback DROP TABLE scopes;

-- changeset albert:5-create-rent-spots-table
CREATE TABLE IF NOT EXISTS rent_spots(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES rent_spots(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    area geography(Polygon, 4326) NOT NULL,
    is_parking BOOLEAN NOT NULL
);
CREATE INDEX idx_rent_spots_area ON rent_spots USING GIST(area);
-- rollback DROP TABLE rent_sports;

-- changeset albert:6-create-models-table
CREATE TABLE IF NOT EXISTS models(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL
);
-- rollback DROP TABLE models;

-- changeset albert:7-create-scooters-table
CREATE TABLE IF NOT EXISTS scooters(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no VARCHAR(255) UNIQUE NOT NULL,
    model_id INTEGER NOT NULL REFERENCES models(id),
    battery INTEGER NOT NULL CHECK (battery BETWEEN 0 AND 100),
    location geography(Point, 4326) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('FREE', 'OCCUPIED', 'MAINTENANCE', 'ACTIVATING', 'BLOCKING', 'STOPPING'))
);
CREATE INDEX idx_scooters_location ON scooters USING GIST(location);
-- rollback DROP TABLE scooters;

-- changeset albert:8-create-tariffs-table
CREATE TABLE IF NOT EXISTS tariffs(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    base_price DECIMAL(10, 2) NOT NULL,
    billing_interval_minutes INTEGER CHECK (billing_interval_minutes > 0)
);
-- rollback DROP TABLE tariffs;

-- changeset albert:9-create-subscription-tariffs-table
CREATE TABLE IF NOT EXISTS subscription_tariffs(
    tariff_id INTEGER PRIMARY KEY REFERENCES tariffs(id) ON DELETE CASCADE,
    duration_days INTEGER NOT NULL
);
-- rollback DROP TABLE subscription_tariffs;

-- changeset albert:10-create-user-subscriptions-table
CREATE TABLE IF NOT EXISTS user_subscriptions(
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    tariff_id INTEGER NOT NULL REFERENCES tariffs(id) ON DELETE CASCADE,
    next_billing_date DATE NOT NULL
);
-- rollback DROP TABLE user_subscriptions;

-- changeset albert:11-create-role-scope-table
CREATE TABLE IF NOT EXISTS role_scope(
    role_id INTEGER REFERENCES roles(id),
    scope_id INTEGER REFERENCES scopes(id),
    PRIMARY KEY (role_id, scope_id)
);
-- rollback DROP TABLE role_scope;

-- changeset albert:12-create-trips-table
CREATE TABLE IF NOT EXISTS trips(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) CHECK (status IN ('ONGOING', 'PAUSED', 'FINISHED')),
    scooter_id INTEGER NOT NULL REFERENCES scooters(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    started_at TIMESTAMP NOT NULL,

    -- Историческая денормализация
    price_at_start DECIMAL(10, 2) NOT NULL,
    interval_at_start INTEGER,
    discount_at_start DECIMAL(3, 2) CHECK (discount_at_start BETWEEN 0 AND 1),

    -- Заполняется в конце
    duration_seconds INTEGER,

    -- Денормализация итогов
    distance FLOAT,
    route geography(LineString, 4326),
    total_price NUMERIC(10, 2)
);
-- rollback DROP TABLE trips;

-- changeset albert:13-create-trip-points-table
CREATE TABLE IF NOT EXISTS trip_points(
    trip_id INTEGER REFERENCES trips(id),
    location geography(Point, 4326) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (trip_id, created_at)
);
-- rollback DROP TABLE trip_points;

-- changeset albert:14-create-sessions-table
CREATE TABLE IF NOT EXISTS sessions(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- тех. поля
    refresh_token VARCHAR(255) NOT NULL UNIQUE, -- автоматически создается index (unique)
    replaced_by_token VARCHAR(255) REFERENCES sessions(refresh_token),

    -- поля бизнес логики
    user_id INTEGER NOT NULL REFERENCES users(id),
    device_name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(15) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    terminated BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
-- rollback DROP TABLE sessions;

-- Для работы ShedLock в Scheduler
-- changeset albert:15-create-shedlock-table
CREATE TABLE IF NOT EXISTS shedlock(
    name VARCHAR(64) PRIMARY KEY,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULl
);
-- rollback DROP TABLE shedlock;

-- changeset albert:16-create-billing-batch-failures
CREATE TABLE IF NOT EXISTS billing_batch_failures(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    failed_at TIMESTAMP NOT NULL,
    error_message TEXT NOT NULL,
    is_resolved BOOLEAN NOT NULL DEFAULT false
);
-- rollback DROP TABLE billing_batch_failures;

-- changeset albert:17-create-billing-batch-failure-items
CREATE TABLE IF NOT EXISTS billing_batch_failure_items(
    failure_id INT NOT NULL REFERENCES billing_batch_failures(id),
    user_subscription_id INT NOT NULL -- без FK, т.к. это данные лога
);
-- rollback DROP TABLE billing_batch_failure_items;