# APP
tariff.default-tariff.id=1
rental.minimal-balance=10
role.default-role.id=1
billing.batch.size=100
telemetry.batch.size=100
scooter.minimal-battery=10

# HIBERNATE
hibernate.jdbc.batch-size=50

# KAFKA
kafka.bootstrap-servers=kafka-1:9092

# AUTH
auth.jwt.secret-key=12345678123456781234567812345678
auth.jwt.expiration-time=900000
auth.refresh-token.expiration-time=604800000
auth.refresh-token.retention-time=259200000

# REDIS
redis.host=redis
redis.port=6379
redis.password=test